config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :patients do
	resources :visits
end
root 'patients#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hospital.rb
class Hospital < ApplicationRecord
	has_many :patients
end

app/models/patient.rb
  class Patient < ApplicationRecord
	belongs_to :user
	belongs_to :hospital
	has_many :visits
end

app/models/request.rb
class Request < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_many :patients
	has_many :visits
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/visit.rb
 class Visit < ApplicationRecord
	belongs_to :patient
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
before_action :find_patient, only: [:show, :edit, :update, :destroy]
	
#display all the patients name in the index
	def index 
		@patients = Patient.all.order("created_at DESC") 
	end

	def index
	if params[:hospital].blank? 
      @patients = Patient.all.order("created_at DESC")
    else
      @hospital_id = Hospital.find_by(name: params[:hospital]).id
      @patients = Patient.where(:hospital_id => @hospital_id).order("created_at DESC")
    end
	end


	def show
	end


	# when we create a new patient 
	def new 
		@patient = current_user.patients.build
		@hospitals = Hospital.all.map{ |c| [c.name, c.id] }
	end

	# smae a new patient but will accept the params 
	def create
    @patient = current_user.patients.build (patient_params)
    @patient.hospital_id = params[:hospital_id] 

    if @patient.save
      redirect_to root_path
    else
      render 'new'
    end
  end
	def edit
		@hospitals = Hospital.all.map{ |c| [c.name, c.id] }
	end

	def update
		@patient.hospital_id = params[:hospital_id]  
		if @patient.update(patient_params)
			redirect_to patient_path(@patient)
		else
			render 'edit'
		end
	end

	def destroy
		@patient.destroy
		redirect_to root_path
	end

	private 
		# patietns params-  when a user fills the  form 
		def patient_params
			params.require(:patient).permit(:name, :dob, :address, :phone, :hospital_id)
		end

		def find_patient
			@patient = Patient.find(params[:id])
		end

end

app/controllers/visits_controller.rb
   class VisitsController < ApplicationController
   	before_action :find_patient
   	before_action :find_visit, only: [:edit, :update, :destroy]
	
	def new
		@visit = Visit.new
	end

	def create
		@visit = Visit.new(visit_params)
		@visit.patient_id = @patient.id
		@visit.user_id = current_user.id

		if@visit.save
			redirect_to patient_path(@patient)
		else 
			render 'new'
		end
	end

	def edit
	end

	def update
		@visit = Visit.find(params[:id])

		if @visit.update(visit_params)
			 redirect_to patient_path(@patient)
			 else
			 	render 'edit'
			 end
 	end


	def destroy
	
		@visit.destroy
		 redirect_to patient_path(@patient)
	end


	private

	def visit_params
		params.require(:visit).permit(:hospital, :department, :comment, :date)
	end

	def find_patient
		@patient = Patient.find(params[:patient_id])
	end

	def find_visit
		@visit = Visit.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartHealth</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <nav class="navbar navbar-default">

      <div class="container">

         <div class="navbar-header">
          <%= link_to "Smart | Health", root_path, class: "navbar-brand" %>
         </div>

         <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to "Sign Up", new_user_registration_path %></li>

        <% if user_signed_in? %>

        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>

        <% else %>
        <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
        </ul>

      <ul class="nav navbar-nav">

        <% if user_signed_in? %>
          <li><%= link_to "Add Patient", new_patient_path %></li>
        <% end %> 

        <li class="dropdown">  
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
          Hospitals: <span class="caret"></span>
        <ul class="dropdown-menu" role="menu">
            <% Hospital.all.each do |hospital| %>
              <li class="<%= 'active' if params[:hospital] == hospital.name %>">
                <%= link_to hospital.name, patients_path(hospital: hospital.name), class: "link" %>
              </li>
          <% end %>
          </ul>
        </li>
      </ul>
      



      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  	
    <%= yield %>
  
  </body>
</html>

app/views/patients/_form.html.erb
<%# using the simple form to help users create new patient%>
<%= simple_form_for @patient do |f| %>

<%= select_tag(:hospital_id, options_for_select(@hospitals), :prompt => "Select a Hospital") %>

<%= f.input :name, label: "Full Name" %>
<%= f.input :dob, label: "Date of Birth" %> 
<%= f.input :address, label: "Full Address" %>
<%= f.input :phone, label: "Phone Number"%>
<%#= f.input :hospital, label: "Hospital" %>

<%= f.button :submit %>

<% end %>

app/views/patients/edit.html.erb
 <h1>Edit Patient Details </h1>

<%= simple_form_for @patient do |f| %>

<%= f.select :hospital_id, @hospitals %>

<%= f.input :name, label: "Full Name" %>
<%= f.input :dob, label: "Date of Birth" %> 
<%= f.input :address, label: "Full Address" %>
<%= f.input :phone, label: "Phone Number"%>

<%= f.button :submit %>

<% end %>

app/views/patients/index.html.erb
<h1 class="current-hospital"><%= params[:hospital] %></h1>
<div>
<% if @patients.count == 0 %>

	<h1>There is no patients from this clinic </h1>

<% else %>
<% @patients.each do |patient| %>
<div class="reviews">

	<h2><%= link_to patient.name, patient_path(patient) %></h2>
</div>

<% end %>
<% end %>

</div>

app/views/patients/new.html.erb
<h1> New Patient</h1>


<%# add form to create new patient %>
<%= render 'form' %>

app/views/patients/show.html.erb
<div>

<div class="col-md-8">

	<div class="patient-info">

			<h2 class="patient-name">  <%= @patient.name %> </h2>
			<p class= " "> Date of Birth: <%= @patient.dob %></p>
			<p class= "details"> Address: <%= @patient.address %></p>
			<p class= "details"> Phone Number: <%= @patient.phone %></p>
			<p class= "details"> Hospital: <%= @patient.hospital.name %></p>
	</div>


<% if user_signed_in? %>
	<% if @patient.user_id == current_user.id %>
		<%= link_to "Edit", edit_patient_path(@patient), class: "btn-custom" %>
		<%= link_to "Delete", patient_path(@patient), method: :delete, data: { confirm: "Are you Sure you want to delte the patient?"}, class: "btn-custom" %>
	<% end %>
<% end %>

</div>

	<div class="col-md-4"> 

			<div class="reviews">
		
		<h1> Recent Visits </h1>
			<%= render @patient.visits %>

			<%= link_to "Add Visit Information", new_patient_visit_path(@patient), class: "btn-custom" %>

	</div>

</div>

app/views/visits/_form.html.erb
<%= simple_form_for([@patient, @patient.visits.build]) do |f| %>

<%= f.input :hospital %>
<%= f.input :department %>
<%= f.input :comment %>
<%= f.input :date %>
<%= f.button :submit %>
<% end %>

app/views/visits/_visit.html.erb
<div class="visit">
		<p class="visit-comment"><%= visit.hospital %></p>
		<p class="visit-comment"><%= visit.department %></p>
		<p class="visit-comment"><%= visit.comment %></p>
		<p class="visit-comment"><%= visit.date %></p>

		<div class="links btn-group"></div>

			<%= link_to "Edit", edit_patient_visit_path(visit.patient, visit), class: "btn btn-custom" %>

			<%= link_to "Delete", patient_visit_path(visit.patient, visit), method: :delete, data: { confirm: " Are you Sure??"}, class: "btn btn-custom" %>
 
		</div>
</div>

app/views/visits/edit.html.erb
<h1>Edit Visit</h1>

<%= simple_form_for([@patient , @visit]) do |f| %>
	<%= f.input :hospital %>
	<%= f.input :department %>
	<%= f.input :comment %>
	<%= f.input :date %>
	<%= f.button :submit %>
<% end %>

app/views/visits/new.html.erb
<h1> Visit Information </h1>

<%= render 'form' %>